name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y libyaml-dev
    - name: Build the Docker image
      run: |
        docker build . \
          --file Dockerfile \
          --build-arg DEBIAN_FRONTEND=noninteractive \
          --build-arg BUILD_PACKAGES="libyaml-dev" \
          --tag hypixelforums:$(date +%s)
